version: '3'

services:
  memoryclient.web:
    image: memoryclient.web
    build:
      context: ./MemoryClient.Web
      dockerfile: Dockerfile

  memoryserver:
    image: memoryserver
    build:
      context: ./MemoryServer
      dockerfile: Dockerfile
