apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: memoryserver
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 5000
  selector:
    app: memoryserver
    tier: frontend