apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memoryclient-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memoryclient-web
        tier: frontend
    spec:
      containers:
        - image: eu.gcr.io/plenary-vim-176019/web:latest
          name: client
          ports:
            - containerPort: 80
              name: http
		  env:
		    - name: ApiProtocol
			  value: http