INSERT INTO "Languages"("EnglishCountryName","EnglishName","IETFTag","NativeCountryName","NativeName") VALUES
 ('South Africa','Afrikaans','af-ZA','South Africa','Afrikaans')
,('Albania','Albanian','sq-AL','Albania','Albanian')
,('Algeria','Arabic','ar-DZ','Algeria','Arabic')
,('Bahrain','Arabic','ar-BH','Bahrain','Arabic')
,('Egypt','Arabic','ar-EG','Egypt','Arabic')
,('Iraq','Arabic','ar-IQ','Iraq','Arabic')
,('Jordan','Arabic','ar-JO','Jordan','Arabic')
,('Kuwait','Arabic','ar-KW','Kuwait','Arabic')
,('Lebanon','Arabic','ar-LB','Lebanon','Arabic')
,('Libya','Arabic','ar-LY','Libya','Arabic')
,('Morocco','Arabic','ar-MA','Morocco','Arabic')
,('Oman','Arabic','ar-OM','Oman','Arabic')
,('Qatar','Arabic','ar-QA','Qatar','Arabic')
,('Saudi Arabia','Arabic','ar-SA','Saudi Arabia','Arabic')
,('Syria','Arabic','ar-SY','Syria','Arabic')
,('Tunisia','Arabic','ar-TN','Tunisia','Arabic')
,('United Arab Emirates','Arabic','ar-AE','United Arab Emirates','Arabic')
,('Yemen','Arabic','ar-YE','Yemen','Arabic')
,('Armenia','Armenian','hy-AM','Armenia','Armenian')
,('Azerbaijan','Azeri (Cyrillic)','Cy-az-AZ','Azerbaijan','Azeri (Cyrillic)')
,('Azerbaijan','Azeri (Latin)','Lt-az-AZ','Azerbaijan','Azeri (Latin)')
,('Basque','Basque','eu-ES','Basque','Basque')
,('Belarus','Belarusian','be-BY','Belarus','Belarusian')
,('Bulgaria','Bulgarian','bg-BG','Bulgaria','Bulgarian')
,('Catalan','Catalan','ca-ES','Catalan','Catalan')
,('China','Chinese','zh-CN','China','Chinese')
,('Hong Kong SAR','Chinese','zh-HK','Hong Kong SAR','Chinese')
,('Macau SAR','Chinese','zh-MO','Macau SAR','Chinese')
,('Singapore','Chinese','zh-SG','Singapore','Chinese')
,('Taiwan','Chinese','zh-TW','Taiwan','Chinese')
,('Simplified','Chinese','zh-CHS','Simplified','Chinese')
,('Traditional','Chinese','zh-CHT','Traditional','Chinese')
,('Croatia','Croatian','hr-HR','Croatia','Croatian')
,('Czech Republic','Czech','cs-CZ','Czech Republic','Czech')
,('Denmark','Danish','da-DK','Denmark','Danish')
,('Maldives','Dhivehi','div-MV','Maldives','Dhivehi')
,('Belgium','Dutch','nl-BE','Belgium','Dutch')
,('The Netherlands','Dutch','nl-NL','The Netherlands','Dutch')
,('Australia','English','en-AU','Australia','English')
,('Belize','English','en-BZ','Belize','English')
,('Canada','English','en-CA','Canada','English')
,('Caribbean','English','en-CB','Caribbean','English')
,('Ireland','English','en-IE','Ireland','English')
,('Jamaica','English','en-JM','Jamaica','English')
,('New Zealand','English','en-NZ','New Zealand','English')
,('Philippines','English','en-PH','Philippines','English')
,('South Africa','English','en-ZA','South Africa','English')
,('Trinidad and Tobago','English','en-TT','Trinidad and Tobago','English')
,('United Kingdom','English','en-GB','United Kingdom','English')
,('United States','English','en-US','United States','English')
,('Zimbabwe','English','en-ZW','Zimbabwe','English')
,('Estonia','Estonian','et-EE','Estonia','Estonian')
,('Faroe Islands','Faroese','fo-FO','Faroe Islands','Faroese')
,('Iran','Farsi','fa-IR','Iran','Farsi')
,('Finland','Finnish','fi-FI','Finland','Finnish')
,('Belgium','French','fr-BE','Belgium','French')
,('Canada','French','fr-CA','Canada','French')
,('France','French','fr-FR','France','French')
,('Luxembourg','French','fr-LU','Luxembourg','French')
,('Monaco','French','fr-MC','Monaco','French')
,('Switzerland','French','fr-CH','Switzerland','French')
,('Galician','Galician','gl-ES','Galician','Galician')
,('Georgia','Georgian','ka-GE','Georgia','Georgian')
,('Austria','German','de-AT','Austria','German')
,('Germany','German','de-DE','Germany','German')
,('Liechtenstein','German','de-LI','Liechtenstein','German')
,('Luxembourg','German','de-LU','Luxembourg','German')
,('Switzerland','German','de-CH','Switzerland','German')
,('Greece','Greek','el-GR','Greece','Greek')
,('India','Gujarati','gu-IN','India','Gujarati')
,('Israel','Hebrew','he-IL','Israel','Hebrew')
,('India','Hindi','hi-IN','India','Hindi')
,('Hungary','Hungarian','hu-HU','Hungary','Hungarian')
,('Iceland','Icelandic','is-IS','Iceland','Icelandic')
,('Indonesia','Indonesian','id-ID','Indonesia','Indonesian')
,('Italy','Italian','it-IT','Italy','Italian')
,('Switzerland','Italian','it-CH','Switzerland','Italian')
,('Japan','Japanese','ja-JP','Japan','Japanese')
,('India','Kannada','kn-IN','India','Kannada')
,('Kazakhstan','Kazakh','kk-KZ','Kazakhstan','Kazakh')
,('India','Konkani','kok-IN','India','Konkani')
,('Korea','Korean','ko-KR','Korea','Korean')
,('Kazakhstan','Kyrgyz','ky-KZ','Kazakhstan','Kyrgyz')
,('Latvia','Latvian','lv-LV','Latvia','Latvian')
,('Lithuania','Lithuanian','lt-LT','Lithuania','Lithuanian')
,('FYROM','Macedonian','mk-MK','FYROM','Macedonian')
,('Brunei','Malay','ms-BN','Brunei','Malay')
,('Malaysia','Malay','ms-MY','Malaysia','Malay')
,('India','Marathi','mr-IN','India','Marathi')
,('Mongolia','Mongolian','mn-MN','Mongolia','Mongolian')
,('Norway','Norwegian (Bokmål)','nb-NO','Norway','Norwegian (Bokmål)')
,('Norway','Norwegian (Nynorsk)','nn-NO','Norway','Norwegian (Nynorsk)')
,('Poland','Polish','pl-PL','Poland','Polish')
,('Brazil','Portuguese','pt-BR','Brazil','Portuguese')
,('Portugal','Portuguese','pt-PT','Portugal','Portuguese')
,('India','Punjabi','pa-IN','India','Punjabi')
,('Romania','Romanian','ro-RO','Romania','Romanian')
,('Russia','Russian','ru-RU','Russia','Russian')
,('India','Sanskrit','sa-IN','India','Sanskrit')
,('Serbia','Serbian (Cyrillic)','Cy-sr-SP','Serbia','Serbian (Cyrillic)')
,('Serbia','Serbian (Latin)','Lt-sr-SP','Serbia','Serbian (Latin)')
,('Slovakia','Slovak','sk-SK','Slovakia','Slovak')
,('Slovenia','Slovenian','sl-SI','Slovenia','Slovenian')
,('Argentina','Spanish','es-AR','Argentina','Spanish')
,('Bolivia','Spanish','es-BO','Bolivia','Spanish')
,('Chile','Spanish','es-CL','Chile','Spanish')
,('Colombia','Spanish','es-CO','Colombia','Spanish')
,('Costa Rica','Spanish','es-CR','Costa Rica','Spanish')
,('Dominican Republic','Spanish','es-DO','Dominican Republic','Spanish')
,('Ecuador','Spanish','es-EC','Ecuador','Spanish')
,('El Salvador','Spanish','es-SV','El Salvador','Spanish')
,('Guatemala','Spanish','es-GT','Guatemala','Spanish')
,('Honduras','Spanish','es-HN','Honduras','Spanish')
,('Mexico','Spanish','es-MX','Mexico','Spanish')
,('Nicaragua','Spanish','es-NI','Nicaragua','Spanish')
,('Panama','Spanish','es-PA','Panama','Spanish')
,('Paraguay','Spanish','es-PY','Paraguay','Spanish')
,('Peru','Spanish','es-PE','Peru','Spanish')
,('Puerto Rico','Spanish','es-PR','Puerto Rico','Spanish')
,('Spain','Spanish','es-ES','Spain','Spanish')
,('Uruguay','Spanish','es-UY','Uruguay','Spanish')
,('Venezuela','Spanish','es-VE','Venezuela','Spanish')
,('Kenya','Swahili','sw-KE','Kenya','Swahili')
,('Finland','Swedish','sv-FI','Finland','Swedish')
,('Sweden','Swedish','sv-SE','Sweden','Swedish')
,('Syria','Syriac','syr-SY','Syria','Syriac')
,('India','Tamil','ta-IN','India','Tamil')
,('Russia','Tatar','tt-RU','Russia','Tatar')
,('India','Telugu','te-IN','India','Telugu')
,('Thailand','Thai','th-TH','Thailand','Thai')
,('Turkey','Turkish','tr-TR','Turkey','Turkish')
,('Ukraine','Ukrainian','uk-UA','Ukraine','Ukrainian')
,('Pakistan','Urdu','ur-PK','Pakistan','Urdu')
,('Uzbekistan','Uzbek (Cyrillic)','Cy-uz-UZ','Uzbekistan','Uzbek (Cyrillic)')
,('Uzbekistan','Uzbek (Latin)','Lt-uz-UZ','Uzbekistan','Uzbek (Latin)')
,('Vietnam','Vietnamese','vi-VN','Vietnam','Vietnamese')
,('Latin','Latin','la-LA','Latin','Latin');
